name: public
named: {}
views:
  uesio/web.footer: true
  uesio/web.header: true
  uesio/web.home: true
  uesio/web.generate: true
  uesio/web.features_accordion: true
  uesio/web.use_cases: true
  uesio/web.personal_demo: true
  uesio/web.savings: true
  uesio/web.testimonials: true
collections: {}
routes:
  uesio/web.home: true
files: {}
bots: {}
integrationActions: {}
allowallbots: false
allowallcollections: false
allowallviews: false
allowallroutes: false
allowallfiles: true
allowallintegrationactions: false
modifyallrecords: false
viewallrecords: false
