name: public
named: {}
views:
  uesio/web.footer: true
  uesio/web.header: true
  uesio/web.home: true
collections: {}
routes:
  uesio/web.home: true
files: {}
bots: {}
integrationActions: {}
allowallbots: false
allowallcollections: false
allowallviews: false
allowallroutes: false
allowallfiles: true
allowallintegrationactions: false
modifyallrecords: false
viewallrecords: false
