name: public
named: {}
views:
  ben/web.footer: true
  ben/web.header: true
  ben/web.home: true
collections: {}
routes:
  ben/web.home: true
files: {}
bots: {}
integrationActions: {}
allowallbots: false
allowallcollections: false
allowallviews: false
allowallroutes: false
allowallfiles: false
allowallintegrationactions: false
modifyallrecords: false
viewallrecords: false
