name: public
named: {}
views:
  uesio/web.demo: true
  uesio/web.features_accordion: true
  uesio/web.footer: true
  uesio/web.generate: true
  uesio/web.header: true
  uesio/web.home: true
  uesio/web.news: true
  uesio/web.news_article: true
  uesio/web.partners: true
  uesio/web.personal_demo: true
  uesio/web.pricing: true
  uesio/web.privacy: true
  uesio/web.savings: true
  uesio/web.terms: true
  uesio/web.testimonials: true
  uesio/web.use_cases: true
collections: {}
routes:
  uesio/web.demo: true
  uesio/web.home: true
  uesio/web.login: true
  uesio/web.news: true
  uesio/web.news_article: true
  uesio/web.partners: true
  uesio/web.pricing: true
  uesio/web.privacy: true
  uesio/web.terms: true
files: {}
bots:
  uesio/web.request_demo: true
integrationActions: {}
allowallbots: false
allowallcollections: false
allowallviews: false
allowallroutes: false
allowallfiles: true
allowallintegrationactions: false
modifyallrecords: false
viewallrecords: false
