name: default
label: Default
definition:
  uesio.styleTokens:
    root:
      - md:p-8
      - p-6
      - border-y-1
      - border-zinc-200
      - bg-white
      - overflow-auto
      - bg-gradient-to-tr
      - from-zinc-400/10
      - to-transparent
      - "[scrollbar-width:none]"
